BEGIN;

DROP TABLE IF EXISTS INDIVIDUAL, BUSINESS CASCADE;

CREATE TABLE INDIVIDUAL (
  ID SERIAL PRIMARY KEY,
  FIRST_NAME VARCHAR(255) NOT NULL,
  LAST_NAME VARCHAR(255) NOT NULL,
  EMAIL VARCHAR(255) NOT NULL,
  PASSWORD TEXT NOT NULL,
  ADDRESS TEXT NOT NULL,
  GENDER VARCHAR(6) NOT NULL,
  BOD DATE NOT NULL,
  PHONE_NUMBER VARCHAR(20) NOT NULL
);

CREATE TABLE BUSINESS (
  ID SERIAL PRIMARY KEY,
  NAME VARCHAR(255) NOT NULL,
  EMAIL VARCHAR(255) NOT NULL,
  PASSWORD TEXT NOT NULL,
  ADDRESS TEXT NOT NULL,
  PHONE_NUMBER VARCHAR(20) NOT NULL
);

COMMIT;